name: CI/CD Pipeline

on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: voltix-ai-backend  

    steps:
      - uses: actions/checkout@v4

      - name: Debug repo structure
        run: ls -R

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install
      - run: npm test

