name: CI/CD Pipeline

on:
  push:
    branches: [dev]
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test


